#!/bin/bash

# ----------------------------------------------------------------------------
# "THE BEER-WARE LICENSE" (Revision 42):
# guelfoweb@gmail.com wrote this file. As long as you retain this notice you
# can do whatever you want with this stuff. If we meet some day, and you think
# this stuff is worth it, you can buy me a beer in return Gianni Amato
# ----------------------------------------------------------------------------

# Dump Match:
# a simple pattern matching implementation to get the results of the dumps

# Usage:
# dmatch <pattern file> <dir or file dump>

version="1.1"

# check args
if [[ "$1" == "--help" || "$1" == "-h" || "$1" == "" ]]; then
	echo "$0 <pattern file> <dir or file dump>"
	exit
elif [[ "$1" == "--version" || "$1" == "-v" ]]; then
	echo "$0 v.$version"
	exit
elif [[ ! -f "$1" ]]; then
	echo "pattern file not found"
	exit
fi

# recursive grep if $2 is folder
if [[ -f "$2" ]]; then
	RECURSIVE=""
elif [[ -d "$2" ]]; then
	RECURSIVE="-r"
else
	echo "dump not found"
	exit
fi

# constants
timestamp=$(date +'%s')
diroutput="output_$timestamp"
tempfile="$diroutput/.$timestamp"
patterncount=$(wc -l < "$1")

# make output folder
mkdir $diroutput

echo "Looking for $patterncount patterns ..."
echo ""

# move all matches to hidden tempfile
grep -f "$1" $RECURSIVE "$2" >> "$tempfile"

# read pattern file "$1" line by line
while IFS= read -r line
do
	# replace . with \. regex
	rule=$(echo $line | sed 's/\./\\./g')

	# skip blank line or space
	if [[ ! "$rule" =~ ^$ || "$rule" =~ ^[[:space:]]+$ ]]; then
		
		# purge line if rule starts with "." or "@"
		# ex: .domain.com or @domain.com
		line=$(echo $line | sed 's/^[\.|@]//')
		
		# move each match to txt file: $line.txt
		grep "$rule" "$tempfile" >> "$diroutput/$line.txt"
	fi
done < "$1"

# remove empty file from output directory
find "$diroutput" -size 0 -print -delete > /dev/null

# count
finished=$(date +'%s')
time=$(expr $finished - $timestamp)
matches=$(ls "$diroutput" | wc -l)

# remove hidden tempfile
rm "$tempfile"

# show output
wc -l "$diroutput/"* | sed "s/$diroutput\///" | sed 's/\.txt$//' # sort -nr order by count
echo ""
echo "folder -> $diroutput"
echo ""
echo "matched $matches/$patterncount patterns in $time seconds."
exit
